version: '3.8'
services:
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    volumes:
      - ./db-data:/var/lib/mysql
    env_file:
      - docker-db.env
  mc-server:
    image: quickplaymod/quickplay-mc-linking-server
    depends_on:
      - db
    ports:
      - "25565:25565"
    restart: unless-stopped
    env_file:
      - .env
